# Generated by Django 3.0.5 on 2020-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runner_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('shirt_size', models.CharField(max_length=30)),
                ('choose_race', models.CharField(max_length=30)),
            ],
        ),
    ]
