# Generated by Django 3.0.5 on 2020-05-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangalore_jobs',
            name='Slno',
        ),
        migrations.RemoveField(
            model_name='hyderabad_jobs',
            name='Slno',
        ),
        migrations.RemoveField(
            model_name='mumbai_jobs',
            name='Slno',
        ),
        migrations.RemoveField(
            model_name='pune_jobs',
            name='Slno',
        ),
    ]
