# Generated by Django 3.0.5 on 2020-05-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_auto_20200511_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bangalore_jobs',
        ),
        migrations.DeleteModel(
            name='Hyderabad_jobs',
        ),
        migrations.DeleteModel(
            name='Mumbai_jobs',
        ),
        migrations.DeleteModel(
            name='Pune_jobs',
        ),
    ]
