# Generated by Django 3.0.5 on 2020-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('eno', models.IntegerField()),
                ('esal', models.FloatField(max_length=30)),
                ('eaddrs', models.CharField(max_length=30)),
            ],
        ),
    ]
