# Generated by Django 3.0.5 on 2020-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='esal',
            field=models.IntegerField(),
        ),
    ]
