# Generated by Django 3.0.5 on 2020-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20200520_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eaddrs',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=300),
        ),
    ]
