# Generated by Django 3.0.5 on 2020-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rastaurant_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dine', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('foodq', models.CharField(max_length=20)),
                ('services', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('experience', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=256)),
            ],
        ),
    ]
