# Generated by Django 3.0.5 on 2020-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20200516_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastaurant_feedback',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
