# Generated by Django 3.0.5 on 2020-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('clocation', models.CharField(max_length=100)),
                ('cceo', models.CharField(max_length=100)),
            ],
        ),
    ]
