# Generated by Django 3.0.5 on 2020-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('agreement', models.BooleanField()),
            ],
        ),
    ]
