# Generated by Django 3.0.5 on 2020-05-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0002_remove_volunteer_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='agreement',
        ),
    ]
